import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calculation Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Calculation Tools
        </h1>

        <div className={styles.grid}>
          <Link href="/overtime-calculations">
            <a className={styles.card}>
              <h2>時間差分計算 &rarr;</h2>
              <p>
                時間の差分を10進法表記に変換します！<br />
                例: 1:30 → 1.5h, 1:45 → 1.75h
              </p>
            </a>
          </Link>

          <Link href="/weight-calculations">
            <a className={styles.card}>
              <h2>理想の体重計算 &rarr;</h2>
              <p>
                あなたの身長と体重からBMIや標準体重、シンデレラ体重、美容体重を計算します！
              </p>
            </a>
          </Link>

          <Link href="#">
            <a className={styles.card}>
              <h2>Next Update &rarr;</h2>
              <p>Next Update Next Update Next Update Next Update Next Update!</p>
            </a>
          </Link>

          <Link href="#">
            <a className={styles.card}>
              <h2>Next Update &rarr;</h2>
              <p>Next Update Next Update Next Update Next Update Next Update!</p>
            </a>
          </Link>
        </div>
      </main>

      {/* TODO: 文言修正する */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
